version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: production
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - ${POSTGRES_DOCKER_HOST}
  main_db:
    container_name: ${POSTGRES_DOCKER_HOST}
    image: postgres:12
    restart: always
    networks:
      - webnet
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
